### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by Fraser-McLean** [DeyvidKochanov-TomTom/kprnet#15]
Hi,

You mentioned in [this issue](https://github.com/DeyvidKochanov-TomTom/kprnet/issues/7) that you planned to release a fully trained model. Was this ever done? If it was, where I access it from.

Thanks

**Comment by DeyvidKochanov-TomTom** [comment]
Hi,
thanks for the reminder! I have updated the readme with a link to the weights.

**Comment by LeopoldACC** [comment]
> Hi, thanks for the reminder! I have updated the readme with a link to the weights.

It helps me a lot to do my research,Thks a lot!
