### ISSUE TITLE
some question about the projuection

### ISSUE THREAD

**Issue by degagex** [DeyvidKochanov-TomTom/kprnet#18]
Hi,I'm reading you code now,in your projection,I change the threshold (you set it 0.2 and 0.8) to any figure between 0 and 1, but the value of new_raw is always 63,I wonder know why it comes that,thanks a lot!

**Comment by DeyvidKochanov-TomTom** [comment]
Hi,
in [this issue](https://github.com/DeyvidKochanov-TomTom/kprnet/issues/8#issuecomment-762164303) I tried to explain what the values 0.2 and 0.8 are. I don't know why you would need to change them but I guess almost anything will work e.g. setting them to 0.1 and 0.9 would also be okay.  I hope this helps!

**Comment by degagex** [comment]
Thanks!Tom.
HHH,maybe I didn't express my opion clearly,I mean I can't understand that why do this "new_raw = np.nonzero((proj_x[1:] < 0.2) * (proj_x[:-1] > 0.8))[0] + 1" ,the value of new_raw is 63 exactly?

**Comment by DeyvidKochanov-TomTom** [comment]
I am not sure I understand the question if you want to understand the 0.2 and 0.8 values I suggest you look at the other issue. I don't know why for you new_raw always becomes 63, it should be an array which contains the indexes of all points which start a new line in the lidar scan.

**Comment by degagex** [comment]
OK OK，I get it ，thanks alot！



---Original---
From: ***@***.***&gt;
Date: Tue, Jan 25, 2022 20:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [DeyvidKochanov-TomTom/kprnet] some question about the projuection (Issue #18)




 
I am not sure I understand the question if you want to understand the 0.2 and 0.8 values I suggest you look at the other issue. I don't know why for you new_raw always becomes 63, it should be an array which contains the indexes of all points which start a new line in the lidar scan.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by degagex** [comment]
I don't know why for you new_raw always becomes 63, it should be an array which contains the indexes of all points which start a new line in the lidar scan.
I guess because I use SemanticKITTI dataset,it gets data vy velodyne 64？I am just a beginner,so maybe my questions are funny😂



---Original---
From: ***@***.***&gt;
Date: Tue, Jan 25, 2022 20:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [DeyvidKochanov-TomTom/kprnet] some question about the projuection (Issue #18)




 
I am not sure I understand the question if you want to understand the 0.2 and 0.8 values I suggest you look at the other issue. I don't know why for you new_raw always becomes 63, it should be an array which contains the indexes of all points which start a new line in the lidar scan.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DeyvidKochanov-TomTom** [comment]
The code should work with semantic kitti so if you can give an example  by sequence id and point cloud id  I can look at it. But also are you doing any kind of augmentation to the point cloud beforehand like random flipping?  That would break the projection function.

**Comment by degagex** [comment]
I don't do any change of the code,and I use KITTI sequce00 and 000000.bin,iy contains 124668 points.



---Original---
From: ***@***.***&gt;
Date: Tue, Jan 25, 2022 20:56 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [DeyvidKochanov-TomTom/kprnet] some question about theprojuection (Issue #18)




 
The code should work with semantic kitti so if you can give an example  by sequence id and point cloud id  I can look at it. But also are you doing any kind of augmentation to the point cloud beforehand like random flipping?  That would break the projection function.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DeyvidKochanov-TomTom** [comment]
Hi, I tried the scan but it seems okay. Could you put together a minimal example to reproduce your problem? Something similar to this:
https://gist.github.com/DeyvidKochanov-TomTom/9551bb36bbf87f9c7437f70a5ed1173c

**Comment by degagex** [comment]
Hi, I know your code now, this code "new_raw = np.nonzero((proj_x[1:] < 0.2) * (proj_x[:-1] > 0.8))[0] + 1" is used to find the points which begin the new line, 0.8 and 0.2 are not the unique threshold, thanks a lot, you are a nice man 😉!
