### ISSUE TITLE
load model failed

### ISSUE THREAD

**Issue by sunnyln** [DeyvidKochanov-TomTom/kprnet#7]
When I run the inference script, I got an error below:

(env3.7) lina@lina:~/python_code/kprnet-master$ python run_inference.py --checkpoint-path ./resnext_cityscapes_2p.pth --output-path ./results/ --semantic-kitti-dir /home/lina/python_code/SalsaNext-master/dataset/sequences/
resnext_cityscapes_2p.pth
Traceback (most recent call last):
  File "run_inference.py", line 77, in <module>
    main()
  File "run_inference.py", line 40, in main
    model.load_state_dict(torch.load(args.checkpoint_path))
  File "/home/lina/venv/env3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DeepLabKP:
	Missing key(s) in state_dict: "kpclassifier.kpconv.weights", "kpclassifier.kpconv.kernel_points", "kpclassifier.bn.weight", "kpclassifier.bn.bias", "kpclassifier.bn.running_mean", "kpclassifier.bn.running_var", "final.weight", "final.bias". 

could you please kindly tell me why, thx!

**Comment by DeyvidKochanov-TomTom** [comment]
Hi,
these are the pre-training weights from cityscapes not the fully trained model. I can upload the full model later this week.
